---

# Playbook for app server

- name: app server
  hosts: tag_Name_App01 #ec2.py dynamic tag tag_KEY_VALUE
  become: yes
  gather_facts: no

  roles:
    - app
    
  vars:
    wp_mysql_db: terraformansible01
    wp_mysql_user: admindb
    wp_mysql_password: a1s2d3f4
    wp_mysql_host: '{{ db_endpoint }}'